version: '3.8'

services:
  chatbot_db:
    container_name: chatbot_db
    image: "postgres:16.3"
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    command: ["postgres", "-c", "port=${DATABASE_PORT}"]

  chatbot-app:
    build: .
    image: chatbot-app:latest
    container_name: chatbot-app
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_BUFFER_THRESHOLD=${BOT_BUFFER_THRESHOLD}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - chatbot_db
    env_file:
      - ./settings.env